# Generated by Django 6.0.2 on 2026-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_history',
            name='concurrent_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
