# Generated by Django 6.0.2 on 2026-02-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_data',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='app_data',
            old_name='url_test',
            new_name='url',
        ),
    ]
