# Generated by Django 6.0.2 on 2026-03-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unblockuser',
            name='name',
        ),
    ]
