# Generated by Django 6.0.2 on 2026-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_data',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain_logs',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login_logout_history',
            name='token_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
