# Generated by Django 6.0.2 on 2026-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_unblockuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_data',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='app_data',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='unblockuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
