# Generated by Django 6.0.2 on 2026-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_app_data_url_alter_domain_logs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
