# Generated by Django 6.0.2 on 2026-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_history',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
